import { Providers } from '@/providers';
// import type { Metadata } from 'next';
import { CartProvider } from '@/contexts/cart-context';
import { CurrencyProvider } from '@/contexts/currency-context';
import { WishlistProvider } from '@/contexts/wishlist-context';
import { clashDisplay } from '@/lib/fonts';
import { Manrope } from 'next/font/google';
import { Toaster } from 'sonner';
import './globals.css';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${clashDisplay.variable} ${manrope.variable} antialiased`}
      >
        <Providers>
          <CartProvider>
            <WishlistProvider>
              <CurrencyProvider>{children}</CurrencyProvider>
            </WishlistProvider>
          </CartProvider>
          <Toaster position='top-center' richColors />
        </Providers>
      </body>
    </html>
  );
}
